=== KamyNz/rabix/rabix/models/schema/app-docker-wrp.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": ["$$type", "docker_image_ref", "schema", "wrapper"],
    "properties": {
        "$$type": {"enum": ["app/tool/docker-wrapper"]},
        "wrapper_id": {"type": "string"},
        "docker_image_ref": {
            "type": "object",
            "properties": {
                "image_id": {"type": "string"},
                "image_repo": {"type": "string"},
                "image_tag": {"type": "string"}
            }
        },
        "schema": {
            "oneOf": [
                {"$ref": "iodef-sbgsdk.json"},
                {"$ref": "iodef-jsonschema.json"}
            ]
        },
        "wrapper": {
            "type": "object",
            "properties": {
                "base_cmd": {"type": "array", "items": {"type": "string"}},
                "mappings": {"type": "object"},
                "outputs": {"type": "object"},
                "redirect": {"type": "array", "items": {"type": "string"}}
            }
        }
    }
}

=== KamyNz/rabix/rabix/tests/apps/grep.json
{
    "$$type": "app/tool/docker-wrapper",
    "docker_image_ref": {
        "image_id": "b4df48a96d44",
        "image_repo": "images.sbgenomics.com/sevenbridges/sbg_bwa",
        "image_tag": "a019a90500aa39fd"
    }, 
    "schema": {
        "$$type": "schema/app",
        "inputs": {
            "type": "object",
            "required": ["inp"],
            "properties": {
                "inp": {"type": "string"}
            }
        },
        "params": {
            "type": "object",
            "required": ["expr"],
            "properties": {
                "expr": {"type": "string"},
                "context": {"type": "integer"}
            }
        },
        "outputs": {
            "type": "object",
            "properties": {
                "out": {"type": "string"}
            }
        }
    },
    "wrapper": {
        "base_cmd": ["grep"],
        "redirect": ["1>out.txt"],
        "mappings": {
            "expr": 0,
            "inp": 1,
            "context": "-C"
        },
        "outputs": {
            "out": "out.txt"
        }
    }
}
